### ISSUE TITLE
录制后无输出

### ISSUE THREAD

**Issue by Sakuranda** [AsaChiri/DDRecorder#69]
+--------+----------+---------+----------+--------------+---------------------+
|  TID   |   平台   |  房间号 | 直播状态 |   程序状态   |     状态变化时间    |
+--------+----------+---------+----------+--------------+---------------------+
| 332887 | BiliBili | 1991211 |    否    | 正在处理视频 | 2022-06-13 18:33:36 |
+--------+----------+---------+----------+--------------+---------------------+

Traceback (most recent call last):
  File "/root/ddrecorder/DDRecorder-1.2.3/Processor.py", line 117, in concat
    ret = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ffmpeg -y -f concat -safe 0 -i ./data/merge_confs/1991211_2022-06-13_18-32-19_merge_conf.txt -c copy -fflags +igndts -avoid_negative_ts make_zero ./data/merged/1991211_2022-06-13_18-32-19_merged.mp4' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/root/ddrecorder/DDRecorder-1.2.3/Processor.py", line 239, in run
    ret = self.pre_concat()
  File "/root/ddrecorder/DDRecorder-1.2.3/Processor.py", line 180, in pre_concat
    self.live_start = self.times[0][0]
IndexError: list index out of range
使用cookies上传
    DDRecorder  当前时间：2022-06-13 18:34:39.711213 正在工作线程数：2

outputs文件夹里啥也没有 records文件夹里有几个flv但是都是0字节的文件 不知道哪步错了呢
萌新一个 刚学着折腾 还请大佬指教一下x

**Comment by ZhaoWeicheng98** [comment]
您可以将logs文件夹下的日志文件发送到asachiri@outlook.com 以便进一步分析吗
