### ISSUE TITLE
本次登录环境存在风险, 需使用手机号进行验证或绑定

### ISSUE THREAD

**Issue by Sakuranda** [AsaChiri/DDRecorder#72]
【下面是Processor的log】
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 retry.py[line:351] DEBUG Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (1): api.live.bilibili.com:443
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://api.live.bilibili.com:443 "GET /room/v1/Room/get_info?room_id=24402048 HTTP/1.1" 200 None
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 BiliLive.py[line:26] DEBUG [Site:BiliBili Room:24402048] 房间API消息：ok
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://api.live.bilibili.com:443 "GET /live_user/v1/UserInfo/get_anchor_in_room?roomid=24402048 HTTP/1.1" 200 773
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://api.live.bilibili.com:443 "GET /room/v1/Room/get_info?room_id=24402048 HTTP/1.1" 200 None
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 BiliLive.py[line:26] DEBUG [Site:BiliBili Room:24402048] 房间API消息：ok
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://api.live.bilibili.com:443 "GET /live_user/v1/UserInfo/get_anchor_in_room?roomid=24402048 HTTP/1.1" 200 773
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 BaseLive.py[line:66] INFO [Site:BiliBili Room:24402048] 等待开播
Mon, 11 Jul 2022 13:37:30 140254103205440 Thread-3 connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (1): api.bilibili.com:443
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://api.bilibili.com:443 "GET /x/web-interface/nav HTTP/1.1" 200 None
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (1): member.bilibili.com:443
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://member.bilibili.com:443 "GET /x/geetest/pre/add HTTP/1.1" 200 None
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:228] DEBUG Starting new HTTP connection (1): api.bilibili.com:80
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG http://api.bilibili.com:80 "GET /x/space/myinfo HTTP/1.1" 200 None
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 bili_webup.py[line:547] INFO 用户权重: 1
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 bili_webup.py[line:570] INFO 使用客户端api端提交
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:1001] DEBUG Starting new HTTPS connection (1): passport.bilibili.com:443
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://passport.bilibili.com:443 "GET /x/passport-login/web/key HTTP/1.1" 200 None
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 connectionpool.py[line:456] DEBUG https://passport.bilibili.com:443 "POST /x/passport-login/oauth2/login HTTP/1.1" 200 None
Mon, 11 Jul 2022 13:37:31 140254103205440 Thread-3 Uploader.py[line:132] ERROR [Site:BiliBili Room:24402048] Error while uploading:{'code': 0, 'message': '0', 'ttl': 1, 'data': {'status': 2, 'message': '本次登录环境存在风险, 需使用手机号进行验证或绑定', 'url': 'https://passport.bilibili.com/account/mobile/security/managephone/phone/verify?tmp_token=fd076ba81c3cef60b257ee349cfbd171&requestId=5a34c07a963e452b9f911074d4ab736b&source=risk', 'token_info': None, 'cookie_info': None, 'sso': None}}Traceback (most recent call last):
  File "/root/ddrec/DDRecorder-main/Uploader.py", line 124, in upload
    record_video_ret = self.uploader.submit()
  File "/usr/local/lib/python3.10/dist-packages/biliup/plugins/bili_webup.py", line 556, in submit
    ret = self.submit_client()
  File "/usr/local/lib/python3.10/dist-packages/biliup/plugins/bili_webup.py", line 574, in submit_client
    self.login_by_password(**self.account)
  File "/usr/local/lib/python3.10/dist-packages/biliup/plugins/bili_webup.py", line 226, in login_by_password
    raise RuntimeError(r)
RuntimeError: {'code': 0, 'message': '0', 'ttl': 1, 'data': {'status': 2, 'message': '本次登录环境存在风险, 需使用手机号进行验证或绑定', 'url': 'https://passport.bilibili.com/account/mobile/security/managephone/phone/verify?tmp_token=fd076ba81c3cef60b257ee349cfbd171&requestId=5a34c07a963e452b9f911074d4ab736b&source=risk', 'token_info': None, 'cookie_info': None, 'sso': None}}

录制是成功了的 就是上传没对

另外问一下ffmpeg的log【/bin/sh: 1: ffmpeg: not found】是什么情况呢 我设置了环境变量的 直接输入ffmpeg指令能调用出来
还请大佬指教orz

**Comment by ZhaoWeicheng98** [comment]
请尽量用cookie登录，如果你是cookie登录遇到类似问题我在排查一下
