### ISSUE TITLE
录制结束上传报错

### ISSUE THREAD

**Issue by UyNewNas** [AsaChiri/DDRecorder#86]
**Describe the bug**

**To Reproduc

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Traceback (most recent call last):
  File "/usr/src/app/Processor.py", line 118, in concat
    ret = subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ffmpeg -y -f concat -safe 0 -i ./data/merge_confs/22637261_2022-12-28_13-00-33_merge_conf.txt -c copy -fflags +igndts -avoid_negative_ts make_zero ./data/merged/22637261_2022-12-28_13-00-33_merged.mp4' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/src/app/Processor.py", line 251, in run
    ret = self.pre_concat()
  File "/usr/src/app/Processor.py", line 189, in pre_concat
    self.live_start = self.times[0][0]
IndexError: list index out of range

**Comment by ZhaoWeicheng98** [comment]
#87 应该已经帮助修复此问题。
